### ISSUE TITLE
New Submodule and Python 3.10 and GLIBC version Issue

### ISSUE THREAD

**Issue by MaxBial** [avstack-lab/lib-avstack-core#11]
Thanks for the feedback. I was able to fix a few things and confirmed that the following code ran on my end with the latest repo.

Other notable changes: I changed the poetry dependencies base on python3.9 and I added a new submodule. Hopefully this isn't a problem for you.

The perception evaluation does not seem to have the correct output, but the tracking evaluation does, so I'll push this up and figure the percep eval later.

```
import os
import avstack
import avapi
from tqdm import tqdm

%load_ext autoreload
%autoreload 2

data_base = '/data/spencer/'
obj_data_dir_k = os.path.join(data_base, 'KITTI/object')
raw_data_dir_k = os.path.join(data_base, 'KITTI/raw')
obj_data_dir_c = os.path.join(data_base, 'CARLA/carla-object-v1')

KSM = avapi.kitti.KittiScenesManager(obj_data_dir_k, raw_data_dir_k, convert_raw=False)
KDM = KSM.get_scene_dataset_by_index(scene_idx=0)

DM = KDM  # let's use kitti for this one

result_folder = 'results_lidar'
P = avstack.modules.perception.object3d.MMDetObjectDetector3D(
        model='pointpillars', dataset='kitti', threshold=0.7, 
        save_output=True, save_folder=result_folder)
T = avstack.modules.tracking.tracker3d.BasicBoxTracker3D(
        framerate=DM.framerate, save_output=True, save_folder=result_folder)

# detection and tracking
ego_ref = DM.get_ego(frame=0).as_reference()
for frame in tqdm(DM.frames):
    pc = DM.get_lidar(frame, sensor='main_lidar')
    timestamp = DM.framerate * frame
    
    # -- perception
    dets = P(pc, frame=frame, identifier='lidar-detections')
    
    # -- tracking
    tracks = T(detections=dets, t=timestamp, frame=frame, platform=ego_ref)

# %%capture
# ^^ suppress output
percep_res_frames, percep_res_seq, _ = avapi.evaluation.get_percep_results_from_folder(
    DM, P.save_folder, sensor_eval='main_lidar', multiprocess=True)
track_res_frames, track_res_seq, track_res_exp = avapi.evaluation.get_track_results_from_folder(
    DM, T.save_folder, sensor_eval='main_lidar', multiprocess=True)

print('Aggregate perception results:\n', percep_res_seq, '\n')
print('Aggregate tracking results:\n', track_res_seq, '\n')
print('Expanded track metrics include:\n', track_res_exp.keys(), '\n')
print(f'     e.g., HOTA_LocA(0): {track_res_exp["HOTA_LocA(0)"]}')

```

_Originally posted by @roshambo919 in https://github.com/avstack-lab/lib-avstack-core/issues/9#issuecomment-1724226981_
  
So I actually have issues with the new submodules "MiDaS" and "TrackEval" - I have troubles to git clone it. It doesnt work straightforward, so I have to git clone it separately directly from their github repos
The Error is:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:cpsl-research/MiDaS.git' into submodule path '/home/developerpc/AVstack/AVstack_latest/lib-avstack-core/third_party/MiDaS' failed
Failed to clone 'third_party/MiDaS' a second time, aborting
```

Regarding the new python version 3.10 in poetry - I have trouble there because the Kernel is crashing everytime in jupyter notebook but I guess I have to figure it out whats happening on my system.

Sidenote: When installing (git clone) from "carla-sandbox" then the submodules (core and api) are from a different/older version than your "main" - I noticed that because there was still the issue with "modval". I git cloned now the submodules core and api directly (not with the carla-sandbox) and now I will troubleshoot my python 3.10 issue -> but still a hint for you that some dependencies on github for the submodules are not working as suppose to. Or you just planned to migrate carla-sandbox to 3.10 later on and thats why

**Comment by MaxBial** [comment]
Update Regarding the compatibility with python 3.10. I run the "poetry run pytest tests" and the major issue is the GLIBC version. Now avstack requires GLIBC_2.32 but my system only has GLIBC_2.32, see error:

```
=========================== short test summary info ============================
FAILED tests/ego/test_vehicle_ego.py::test_LidarPerceptionAndTrackingVehicle - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/ego/test_vehicle_ego.py::test_LidarCameraPerceptionAndTrackingVehicle - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/modules/perception/test_monoculardepth.py::test_midas_inference - FileNotFoundError: dpt_beit_base_384 weights not found at /home/developerpc...
FAILED tests/modules/perception/test_object2dfv.py::test_mmdet_2d_perception - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/modules/perception/test_object3d.py::test_mmdet_3d_pgd_kitti - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/modules/perception/test_object3d.py::test_mmdet_3d_pillars_nuscenes - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/modules/perception/test_object3d.py::test_mmdet_3d_pillars_nuscenes_memoryview - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/modules/planning/test_planner_backbones.py::test_object_following - AssertionError: assert None == VehicleState car at position <class 'avstack...
```

Changing the GLIBC version on a system could cause big issues actually, so I am wondering which system (ubuntu version and so on) you are using. Either I will reinstall ubuntu accordingly or search for another solution.

Thanks

**Comment by roshambo919** [comment]
Thanks for the solid testing! This is very useful for us.

Updates:
- The submodule cloning issues were because I inadvertently added the repos with ssh instead of the https urls. These should be fixed now. I would recommend a fresh clone of everything just to be sure this all gets reset for you
- Compatibility: yes - I said 3.9 but ultimately had to go with 3.10 because the FLIR Spinnaker group wouldn't give me the source code to build the wheel for 3.9. smh....
- Regarding the GLIBC version issue, I'm looking into that now. I should note that all our machines are updated to Ubuntu 22.04, if that makes a difference. I'll report back when I figure something out.

**Comment by roshambo919** [comment]
@MaxBial could you try upgrading your `libc6` via:
```
sudo apt-get update
sudo apt-get install libc6
```
Following the guidance from: https://askubuntu.com/questions/421642/libc-so-6-version-glibc-2-14-not-found

**Comment by roshambo919** [comment]
I'll try this out on 18.04 and 20.04 VMs this weekend and let you know. Stay tuned!

**Comment by roshambo919** [comment]
Ok @MaxBial I figured this out. The issue was not actually python 3.10 itself but that compiling mmcv-2.0.1 with python3.10 led to a requirement of GLIBC >= 2.32. The simplest way to get around this was for me to build mmcv-2.0.0 instead. That seems to be working on my 22.04 and 20.04 machines.

Can you confirm? Try the latest main branch.

**Comment by MaxBial** [comment]
Hello @roshambo919 thank you for figuring out the issue. I tried the latest main branch and it got for sure better. But for 2 things the same "GLIBC_2.32 not found" error remains, see log:

```
E       ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/developerpc/.cache/pypoetry/virtualenvs/lib-avstack-core-3BYQoD3N-py3.10/lib/python3.10/site-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so)

/usr/lib/python3.10/importlib/__init__.py:126: ImportError
=========================== short test summary info ============================
FAILED tests/ego/test_vehicle_ego.py::test_LidarPerceptionAndTrackingVehicle - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
FAILED tests/ego/test_vehicle_ego.py::test_LidarCameraPerceptionAndTrackingVehicle - ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not foun...
```
When you run this on your 20.04 machine - which GLIBC version you were using? YOu didnt had any issues when running the `poetry run pytest tests` ?

**Comment by roshambo919** [comment]
Oh shoot you're right. Completely missed one thing. Stay tuned...

**Comment by roshambo919** [comment]
Ok NOW I think I've fixed this. It had nothing to do with the 2.0.0 vs 2.0.1 version of mmcv but everything to do with how I built the mmcv wheel. Try the main branch now AND make sure you do the following:
1. Remove the in-use poetry environment `rm -rf ~/.cache/pypoetry/virtualenvs/whateveryoursiscalled`
2. Clear the poetry cache `poetry cache clear --all .` (don't forget the dot at the end)
3. Clear the poetry artifacts `rm -rf ~/.cache/pypoetry/artifacts/*`

There may be a less brute-force approach, but this worked for me. Let me know!

**Comment by MaxBial** [comment]
Hello @roshambo919 , now I do not have any errors running the pytest. Thanks.

Now I could start testing in jupyter notebook - I would like to test it directly in the carla-sandbox. Is the Carla-sandbox up-to-date regarding those changes? I guess so, right?

**Comment by roshambo919** [comment]
Hi Max - if you're running in a jupyter notebook, it would be better to use the [avdev sandbox](https://github.com/avstack-lab/avdev-sandbox) unless you're also using carla outside the notebook.

The avdev-sandbox is not yet up to date and neither is the carla-sandbox, but I'll try to update all dependencies by tomorrow afternoon. Let's discuss over there if you have issues after that.

**Comment by ronyshaji** [comment]
Hey @roshambo919 

I have the same error coming while trying to use the carla-sandbox.
The 'main branch' you mentioned is not clear to me whether it is for the carla-sandbox or lib-avstack-core or  lib-avstack-api.
I checked the sub module branch from the carla-sanddbox repo and found that it is pointed some detached head.
I tried changed manually to main branch for both lib-avstack-core and lib-avstack-api.

Then deleted the virtual environment and followed the steps from 'poetry install'. But ending up with the same error.

`ImportError: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found (required by /home/going/carla-sandbox/.venv/lib/python3.10/site-packages/carla/libcarla.cpython-310-x86_64-linux-gnu.so)`

Thanks and waiting for your feedback

**Comment by roshambo919** [comment]
It’s possible the submodule reference to AVstack on the sandbox is out of
date. I’ll check it out and get back to you.

**Comment by ronyshaji** [comment]
@roshambo919 Thanks for the answer. Waiting for the feedback.

**Comment by roshambo919** [comment]
@ronyshaji inspecting your error output, it seems your error more likely comes from a carla-specific dependency, so therefore I've moved the issue over to: https://github.com/avstack-lab/carla-sandbox/issues/4
